"""Sprint 21.8 — Corpus para classificação de dependência de contexto.

200 frases (100 COMPLETE_REFERENCE + 100 CONTEXT_DEPENDENT) + 7 ambíguos.
"""

# Classe, frase
CORPUS = [
    # ===== COMPLETE_REFERENCE (100) =====
    # Salmos e sabedoria (20)
    ("COMPLETE_REFERENCE", "O Senhor é meu pastor."),
    ("COMPLETE_REFERENCE", "Ainda que eu ande pelo vale da sombra da morte."),
    ("COMPLETE_REFERENCE", "O Senhor é a minha luz e a minha salvação."),
    ("COMPLETE_REFERENCE", "Entrega o teu caminho ao Senhor."),
    ("COMPLETE_REFERENCE", "Alegrei-me quando me disseram vamos à casa do Senhor."),
    ("COMPLETE_REFERENCE", "Deus é o nosso refúgio e fortaleza."),
    ("COMPLETE_REFERENCE", "Cria em mim um coração puro."),
    ("COMPLETE_REFERENCE", "Os céus declaram a glória de Deus."),
    ("COMPLETE_REFERENCE", "Quem subirá ao monte do Senhor."),
    ("COMPLETE_REFERENCE", "Lâmpada para os meus pés é a tua palavra."),
    ("COMPLETE_REFERENCE", "Tudo tem o seu tempo determinado."),
    ("COMPLETE_REFERENCE", "Perto está o Senhor dos que têm o coração quebrantado."),
    ("COMPLETE_REFERENCE", "Guarda o teu coração com toda a diligência."),
    ("COMPLETE_REFERENCE", "O temor do Senhor é o princípio do conhecimento."),
    ("COMPLETE_REFERENCE", "Confia no Senhor de todo o teu coração."),
    ("COMPLETE_REFERENCE", "Vaidade de vaidades tudo é vaidade."),
    ("COMPLETE_REFERENCE", "Melhor é a sabedoria que a força."),
    ("COMPLETE_REFERENCE", "A resposta branda desvia o furor."),
    ("COMPLETE_REFERENCE", "O orgulho vai adiante da ruína."),
    ("COMPLETE_REFERENCE", "Instrui o menino no caminho em que deve andar."),
    # Evangelhos (25)
    ("COMPLETE_REFERENCE", "Porque Deus amou o mundo de tal maneira."),
    ("COMPLETE_REFERENCE", "Buscai primeiro o Reino de Deus."),
    ("COMPLETE_REFERENCE", "Vinde a mim todos os que estais cansados."),
    ("COMPLETE_REFERENCE", "Eu sou o caminho a verdade e a vida."),
    ("COMPLETE_REFERENCE", "A paz eu vos deixo a minha paz vos dou."),
    ("COMPLETE_REFERENCE", "Bem-aventurados os pobres de espírito."),
    ("COMPLETE_REFERENCE", "Bem-aventurados os que choram."),
    ("COMPLETE_REFERENCE", "Bem-aventurados os mansos."),
    ("COMPLETE_REFERENCE", "Ninguém pode servir a dois senhores."),
    ("COMPLETE_REFERENCE", "Pedra sobre a qual edificarei a minha igreja."),
    ("COMPLETE_REFERENCE", "As raposas têm covis e as aves do céu têm ninhos."),
    ("COMPLETE_REFERENCE", "A seara é grande mas os trabalhadores são poucos."),
    ("COMPLETE_REFERENCE", "Quem quiser vir após mim tome a sua cruz."),
    ("COMPLETE_REFERENCE", "Nem todo o que me diz Senhor Senhor entrará no Reino dos céus."),
    ("COMPLETE_REFERENCE", "Muitos são chamados mas poucos escolhidos."),
    ("COMPLETE_REFERENCE", "A quem muito foi dado muito será exigido."),
    ("COMPLETE_REFERENCE", "O espírito é o que vivifica a carne para nada aproveita."),
    ("COMPLETE_REFERENCE", "Eu sou a videira vós sois os ramos."),
    ("COMPLETE_REFERENCE", "No mundo tereis aflições mas tende bom ânimo."),
    ("COMPLETE_REFERENCE", "Conhecereis a verdade e a verdade vos libertará."),
    ("COMPLETE_REFERENCE", "Bem-aventurados os limpos de coração."),
    ("COMPLETE_REFERENCE", "Bem-aventurados os misericordiosos."),
    ("COMPLETE_REFERENCE", "Bem-aventurados os pacificadores."),
    ("COMPLETE_REFERENCE", "Vós sois a luz do mundo."),
    ("COMPLETE_REFERENCE", "Vós sois o sal da terra."),
    ("COMPLETE_REFERENCE", "Amai os vossos inimigos."),
    # Cartas paulinas (20)
    ("COMPLETE_REFERENCE", "Tudo posso naquele que me fortalece."),
    ("COMPLETE_REFERENCE", "O justo viverá pela fé."),
    ("COMPLETE_REFERENCE", "Porque pela graça sois salvos mediante a fé."),
    ("COMPLETE_REFERENCE", "A armadura de Deus."),
    ("COMPLETE_REFERENCE", "Revesti-vos do novo homem."),
    ("COMPLETE_REFERENCE", "O amor de Cristo nos constrange."),
    ("COMPLETE_REFERENCE", "Não vos conformeis com este mundo."),
    ("COMPLETE_REFERENCE", "Toda a Escritura é divinamente inspirada."),
    ("COMPLETE_REFERENCE", "Porque para mim o viver é Cristo."),
    ("COMPLETE_REFERENCE", "A minha graça te basta."),
    ("COMPLETE_REFERENCE", "Sede imitadores de Deus como filhos amados."),
    ("COMPLETE_REFERENCE", "Regozijai-vos sempre no Senhor."),
    ("COMPLETE_REFERENCE", "Porque as coisas que se vêem são temporais."),
    ("COMPLETE_REFERENCE", "A fé é o firme fundamento das coisas que se esperam."),
    ("COMPLETE_REFERENCE", "Deixando toda a malícia e todo o engano."),
    ("COMPLETE_REFERENCE", "Sede sóbrios e vigilantes."),
    ("COMPLETE_REFERENCE", "Sede transformados pela renovação do vosso entendimento."),
    ("COMPLETE_REFERENCE", "Revesti-vos de toda a armadura de Deus."),
    ("COMPLETE_REFERENCE", "O fruto do Espírito é amor alegria e paz."),
    ("COMPLETE_REFERENCE", "Sobretudo porém revesti-vos do amor."),
    # Pentateuco e históricos (15)
    ("COMPLETE_REFERENCE", "No princípio criou Deus os céus e a terra."),
    ("COMPLETE_REFERENCE", "Ama o teu próximo como a ti mesmo."),
    ("COMPLETE_REFERENCE", "Eu sou o que sou."),
    ("COMPLETE_REFERENCE", "Não terás outros deursos diante de mim."),
    ("COMPLETE_REFERENCE", "Honra teu pai e tua mãe."),
    ("COMPLETE_REFERENCE", "Não matarás."),
    ("COMPLETE_REFERENCE", "O Senhor pelejará por vós e vós vos calareis."),
    ("COMPLETE_REFERENCE", "Vós sereis para mim reino sacerdotal e povo santo."),
    ("COMPLETE_REFERENCE", "Ouve Israel o Senhor nosso Deus é o único Senhor."),
    ("COMPLETE_REFERENCE", "Escolhei hoje a quem sirvais."),
    ("COMPLETE_REFERENCE", "Sê forte e corajoso."),
    ("COMPLETE_REFERENCE", "O Senhor não vê como vê o homem."),
    ("COMPLETE_REFERENCE", "Tua casa e teu reino serão firmados para sempre."),
    ("COMPLETE_REFERENCE", "Se o meu povo que se chama pelo meu nome se humilhar."),
    ("COMPLETE_REFERENCE", "Para o homem é impossível mas para Deus tudo é possível."),
    # Profetas (10)
    ("COMPLETE_REFERENCE", "Eis que a virgem conceberá e dará à luz um filho."),
    ("COMPLETE_REFERENCE", "Porque um menino nos nasceu um filho se nos deu."),
    ("COMPLETE_REFERENCE", "Os que esperam no Senhor renovarão as suas forças."),
    ("COMPLETE_REFERENCE", "Não vos lembreis das coisas passadas."),
    ("COMPLETE_REFERENCE", "Buscai-me e vivereis."),
    ("COMPLETE_REFERENCE", "Como são formosos os pés dos que anunciam o evangelho."),
    ("COMPLETE_REFERENCE", "Dar-vos-ei coração novo e porei dentro de vós espírito novo."),
    ("COMPLETE_REFERENCE", "Porque eu bem sei os pensamentos que penso de vós."),
    ("COMPLETE_REFERENCE", "Converta-se o ímpio do seu caminho."),
    ("COMPLETE_REFERENCE", "Não por força nem por violência mas pelo meu Espírito."),
    # Explícitas (10)
    ("COMPLETE_REFERENCE", "Provérbios 15:14"),
    ("COMPLETE_REFERENCE", "João 3:16"),
    ("COMPLETE_REFERENCE", "Salmos 23"),
    ("COMPLETE_REFERENCE", "Romanos 8:28"),
    ("COMPLETE_REFERENCE", "Filipenses 4:13"),
    ("COMPLETE_REFERENCE", "Gênesis 1:1"),
    ("COMPLETE_REFERENCE", "Isaías 53:5"),
    ("COMPLETE_REFERENCE", "Mateus 5:3"),
    ("COMPLETE_REFERENCE", "Apocalipse 3:20"),
    ("COMPLETE_REFERENCE", "Salmo 91"),

    # ===== CONTEXT_DEPENDENT (100) =====
    # Referências anafóricas explícitas (25)
    ("CONTEXT_DEPENDENT", "Como vimos anteriormente."),
    ("CONTEXT_DEPENDENT", "Esse mesmo versículo."),
    ("CONTEXT_DEPENDENT", "A mesma passagem."),
    ("CONTEXT_DEPENDENT", "Voltando ao texto."),
    ("CONTEXT_DEPENDENT", "No capítulo anterior."),
    ("CONTEXT_DEPENDENT", "Esse texto."),
    ("CONTEXT_DEPENDENT", "Esse capítulo."),
    ("CONTEXT_DEPENDENT", "Esse versículo."),
    ("CONTEXT_DEPENDENT", "Aquela passagem."),
    ("CONTEXT_DEPENDENT", "Aquele texto."),
    ("CONTEXT_DEPENDENT", "Como Paulo disse."),
    ("CONTEXT_DEPENDENT", "Como acabamos de ler."),
    ("CONTEXT_DEPENDENT", "Como vimos no início."),
    ("CONTEXT_DEPENDENT", "Como já falamos."),
    ("CONTEXT_DEPENDENT", "Conforme mencionamos antes."),
    ("CONTEXT_DEPENDENT", "Voltando ao versículo anterior."),
    ("CONTEXT_DEPENDENT", "A passagem de antes."),
    ("CONTEXT_DEPENDENT", "O texto que lemos."),
    ("CONTEXT_DEPENDENT", "Como dissemos antes."),
    ("CONTEXT_DEPENDENT", "Aquele salmo."),
    ("CONTEXT_DEPENDENT", "Como o pastor explicou."),
    ("CONTEXT_DEPENDENT", "Como vimos no último estudo."),
    ("CONTEXT_DEPENDENT", "Como já estudamos."),
    ("CONTEXT_DEPENDENT", "Voltando àquele ponto."),
    ("CONTEXT_DEPENDENT", "Como o apóstolo disse."),
    # Pronomes demonstrativos (20)
    ("CONTEXT_DEPENDENT", "Esse."),
    ("CONTEXT_DEPENDENT", "Essa."),
    ("CONTEXT_DEPENDENT", "Aquele."),
    ("CONTEXT_DEPENDENT", "Aquela."),
    ("CONTEXT_DEPENDENT", "Isso."),
    ("CONTEXT_DEPENDENT", "Aquilo."),
    ("CONTEXT_DEPENDENT", "Ali."),
    ("CONTEXT_DEPENDENT", "Lá."),
    ("CONTEXT_DEPENDENT", "Aqui."),
    ("CONTEXT_DEPENDENT", "Onde estávamos."),
    ("CONTEXT_DEPENDENT", "O que falamos."),
    ("CONTEXT_DEPENDENT", "O que lemos."),
    ("CONTEXT_DEPENDENT", "O que vimos."),
    ("CONTEXT_DEPENDENT", "Como dissemos."),
    ("CONTEXT_DEPENDENT", "Como vimos."),
    ("CONTEXT_DEPENDENT", "Como lemos."),
    ("CONTEXT_DEPENDENT", "Como falamos."),
    ("CONTEXT_DEPENDENT", "Como estudamos."),
    ("CONTEXT_DEPENDENT", "Como lemos antes."),
    ("CONTEXT_DEPENDENT", "Como vimos agora."),
    # Frases elípticas (20)
    ("CONTEXT_DEPENDENT", "O mesmo."),
    ("CONTEXT_DEPENDENT", "A mesma."),
    ("CONTEXT_DEPENDENT", "Os mesmos."),
    ("CONTEXT_DEPENDENT", "As mesmas."),
    ("CONTEXT_DEPENDENT", "Também."),
    ("CONTEXT_DEPENDENT", "Igualmente."),
    ("CONTEXT_DEPENDENT", "Da mesma forma."),
    ("CONTEXT_DEPENDENT", "Do mesmo jeito."),
    ("CONTEXT_DEPENDENT", "Como antes."),
    ("CONTEXT_DEPENDENT", "Como sempre."),
    ("CONTEXT_DEPENDENT", "Outra vez."),
    ("CONTEXT_DEPENDENT", "Novamente."),
    ("CONTEXT_DEPENDENT", "De novo."),
    ("CONTEXT_DEPENDENT", "Mais uma vez."),
    ("CONTEXT_DEPENDENT", "Como já vimos."),
    ("CONTEXT_DEPENDENT", "Como já lemos."),
    ("CONTEXT_DEPENDENT", "Como já dissemos."),
    ("CONTEXT_DEPENDENT", "Como já estudamos."),
    ("CONTEXT_DEPENDENT", "Como já falamos."),
    ("CONTEXT_DEPENDENT", "Como já mencionamos."),
    # Frases com "anterior", "posterior", "próximo" (15)
    ("CONTEXT_DEPENDENT", "No versículo anterior."),
    ("CONTEXT_DEPENDENT", "No texto anterior."),
    ("CONTEXT_DEPENDENT", "No salmo anterior."),
    ("CONTEXT_DEPENDENT", "No livro anterior."),
    ("CONTEXT_DEPENDENT", "Na passagem anterior."),
    ("CONTEXT_DEPENDENT", "No próximo versículo."),
    ("CONTEXT_DEPENDENT", "No próximo capítulo."),
    ("CONTEXT_DEPENDENT", "Na próxima passagem."),
    ("CONTEXT_DEPENDENT", "Mais à frente."),
    ("CONTEXT_DEPENDENT", "Mais adiante."),
    ("CONTEXT_DEPENDENT", "No início do capítulo."),
    ("CONTEXT_DEPENDENT", "No final do texto."),
    ("CONTEXT_DEPENDENT", "No começo do estudo."),
    ("CONTEXT_DEPENDENT", "No fim da carta."),
    ("CONTEXT_DEPENDENT", "No meio da passagem."),
    # Frases curtas contextuais (10)
    ("CONTEXT_DEPENDENT", "Aquele versículo."),
    ("CONTEXT_DEPENDENT", "Aquela parte."),
    ("CONTEXT_DEPENDENT", "Como Pedro disse."),
    ("CONTEXT_DEPENDENT", "Como João disse."),
    ("CONTEXT_DEPENDENT", "Como Isaías disse."),
    ("CONTEXT_DEPENDENT", "Como Davi disse."),
    ("CONTEXT_DEPENDENT", "Como Moisés disse."),
    ("CONTEXT_DEPENDENT", "Como Jesus disse."),
    ("CONTEXT_DEPENDENT", "Como o Senhor disse."),
    ("CONTEXT_DEPENDENT", "Como a Bíblia diz."),
    # Frases parcialmente completas mas dependentes (10)
    ("CONTEXT_DEPENDENT", "O versículo que lemos fala sobre o amor."),
    ("CONTEXT_DEPENDENT", "A passagem que vimos mostra a graça."),
    ("CONTEXT_DEPENDENT", "O texto anterior fala sobre a fé."),
    ("CONTEXT_DEPENDENT", "O capítulo que estudamos trata da esperança."),
    ("CONTEXT_DEPENDENT", "Aquele versículo sobre a salvação."),
    ("CONTEXT_DEPENDENT", "O salmo que lemos ontem."),
    ("CONTEXT_DEPENDENT", "O texto que vimos no início."),
    ("CONTEXT_DEPENDENT", "A passagem que acabamos de ler."),
    ("CONTEXT_DEPENDENT", "O versículo que mencionamos antes."),
    ("CONTEXT_DEPENDENT", "O capítulo que vimos anteriormente."),
]

# Casos ambíguos (análise individual)
AMBIGUOUS = [
    "O bom pastor.",
    "A videira verdadeira.",
    "O pão da vida.",
    "O caminho.",
    "A porta.",
    "A luz do mundo.",
    "O Consolador.",
]
